id: A68AADF06
title: Toh_676-The_Dharani_Essence_of_Immeasurable_Longevity_and_Wisdom-v1
type: translation
pechas:
- I5A7D03F6
- I1BD9A1E8
source_metadata:
  creationtool: InterText
  creationtoolversion: '1.0'
  datatype: PlainText
  segtype: block
  adminlang: en-us
  srclang: bo
  o-tmf: XML aligned text
  eft-text-id: UT22084-091-074
  eft-text-version: 1.0.5 2021
  title: Toh_676-The_Dharani_Essence_of_Immeasurable_Longevity_and_Wisdom-v1
alignment_to_base:
  I5A7D03F6/5830: AA34
  I1BD9A1E8/2963: AA34
